### PR TITLE
New Feature: Auto Colour Update

### PR DESCRIPTION
**Pull request by mrmagic2020**
### Major Changes:
- Fix some data storage bugs.
- Add new feature: auto update stall colour scheme to the configured colour scheme on a daily basis. 
- Update plugin registry metadata. 
- Delete some unnecessary codes.

A very useful plugin, and I feel like making these changes during gameplay 👍

### CODE REVIEW

**Comment by loeppenberg** [comment]
This does no longer work on servers.
Please evaluate the plugin with all these cases:
- Singleplayer
- Hosted Server from GUI
- Headless Server (docker image)

**Comment by mrmagic2020** [comment]
> This does no longer work on servers. Please evaluate the plugin with all these cases:
> 
> * Singleplayer
> * Hosted Server from GUI
> * Headless Server (docker image)

My apologies - I don't usually play servers, so I didn't test it in that environment. Will try and fix.

**Comment by mrmagic2020** [comment]
Tested - it should work now. It turned out that some code I thought was "unnecessary" and deleted was useful in server environments...

**Comment by loeppenberg** [comment]
Thank you for contributing, Pr merged.

**Pull request merged**
